### ISSUE TITLE
Remove all `from [module] import *` code

### ISSUE THREAD

**Issue by aylusltd** [aylusltd/Penguins-in-Python#4]
**Is your feature request related to a problem? Please describe.**
The syntax `from [module] import *` is bad, and should generally feel bad. It creates namespace collisions when modules have properties with the same name. This has already happened during the Python 2>3 migration where importing * from the Python 3 version of `tkinter` overwrote the local `constants` object.

**Describe the solution you'd like**
Remove all instances and limit the imports to what is actually being used.

e.g. from app.py
`from tkinter import Tk, Frame, BOTH, StringVar, Label, Button, Menu`

instead of:
`from tkinter import *`

**Describe alternatives you've considered**
I know the standard in all the tkinter docs is to `import *`, and that's how the project started, but gonna need better discipline as this gets more complicated.

**Additional context**

**Comment by ginglis13** [comment]
Hi - I was looking into taking this on, but it looks like there is no more `from [module] import *` in any file

**Comment by aylusltd** [comment]
check in the sprites folder. Fish.py and spear.py definitely have some.

**Comment by ginglis13** [comment]
ah I see, i missed those. I see that for those files, `from constants import *` is used, which needs to be changed, whereas in some other files, like [keyhandlers.py](https://github.com/aylusltd/Penguins-in-Python/blob/master/keyhandlers.py), `import constants` is used. Would you prefer to change the first one as proposed in the issue or should the second be used?

@aylusltd - @'ing b/c of updates to this comment - any preference^^ ?

**Comment by aylusltd** [comment]
Should wind up like [these](https://github.com/aylusltd/Penguins-in-Python/commit/7d63c6ea80746cbc3f7e4b75ba41a36956c0985a).

```
import constants
from tkinter import [specific], [named], [properties]

...
- random_orphaned_property
+ constants.random_orphaned_property
```
