### ISSUE TITLE
png_to_gif.py doesn't seem to work

### ISSUE THREAD

**Issue by aylusltd** [aylusltd/Penguins-in-Python#7]
**Describe the bug**
Some PNGs are converted fine, others the resulting GIF is useless. It's currently set to run on only one file at a time because replacing the broken gifs is annoying. This should be fixed so there's one prep sprite script to run, instead of all the manual pre-processing.

**Comment by leytpapas** [comment]
The problem i saw in the gifs is to not have transparent background after the edit ('rocks.png'),after some search I got it going

Changed:

https://github.com/aylusltd/Penguins-in-Python/blob/f7ea284dd871fb6f9ae5aff5fa2c3a956f689f05/sprites/png_to_gif.py#L25-L26

to 

```
        # Convert the image into P mode but only use 255 colors in the palette out of 256
        im = im.convert('RGB').convert('P', palette=Image.ADAPTIVE, colors=255)

        # Set all pixel values below 128 to 255 , and the rest to 0
        mask = Image.eval(alpha, lambda a: 255 if a <= 128 else 0)

        # Paste the color of index 255 and use alpha as a mask
        im.paste(255, mask)

        # The transparency index is 255
        im.info['transparency'] = 255
        im.save(new_name)
```


EXTRA:

```
from imp import load_source
constants = load_source('constants', mypath+'/../constants.py')
```
**outputs**
 "DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses"

so I modified it to 

```
import importlib

constants = importlib.machinery.SourceFileLoader('constants', mypath+'/../constants.py')
constants = constants.load_module()
```

Also 
```
mypath = dirname(__file__)
```
didn't seem to take the path at all (tried in windows OS), so I also changed it to 
```
mypath = os.path.dirname(os.path.realpath(__file__))
```

I was exploring random python issues to solve when I found this repo ,so I didn't forked/submitted a pull request, but could do if wanted

**Comment by aylusltd** [comment]
That would be awesome. Please do. I'd love to test it out!

Curious about the `my_path` issue though. That seems really weird. Don't have a windows machine to test on though.

**Comment by leytpapas** [comment]
just published it.
I didn't investigate the conversion for the other modes (P,LA) though.
